### ISSUE TITLE
Initialising OpenSeadragon gives "lacks a call signature" error

### ISSUE THREAD

**Issue by xgfd** [alvaromartmart/types-openseadragon#1]
First thanks a lot for your type definitions. Saved me a lot of time.

In my ts I have the following lines:

```javascript
import OpenSeadragon from "openseadragon";

let osd = OpenSeadragon({...})

```

Since OpenSeadragon is simply a namespace it cannot be invoked. Did you have this issue before? What would be the best way to get around it?

Thanks

**Comment by xgfd** [comment]
I suppose I can use `new OpenSeadragon.Viewer({...})` instead.

**Comment by alvaromartmart** [comment]
Hi @xgfd . Somehow I must have missed the notifications and I didn't see your issues & pull request until today, sorry for that!

As you already figured out I also use `new OpenSeadragon.Viewer({...})` to instantiate the viewer. I guess there may be a more *elegant* way to declare the Viewer as the "main thing", but I'm still learning my way around type declaration files.
