### ISSUE TITLE
ImageTileSource contains the typing "ajaxWidthCredentials" not "ajaxWithCredentials"

### ISSUE THREAD

**Issue by daniel-keller** [alvaromartmart/types-openseadragon#13]
line 595 of index.d.ts has the typing for the class ImageTileSource
```
 class ImageTileSource extends TileSource {
        constructor(options: {
            url: string;
            buildPyramid?: boolean;
            crossOriginPolicy?: string | boolean;
            ajaxWidthCredentials?: string | boolean;
            useCanvas?: boolean;
        });
    }
```
`ajaxWidthCredentials` should be `ajaxWithCredentials`

**Comment by alvaromartmart** [comment]
You're right, that's a typo. I will open a PR request on the DefinitelyTyped repo unless you're already working on it.
(I still need to update this repo to re-direct issues to DefinitelyTyped as I already submitted the typings there, which I think makes a lot more sense)

**Comment by alvaromartmart** [comment]
I already fixed the typo and pushed a PR to DefinitelyTyped, it will hopefully be merged soon

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45724
